Repository viaduct-ai/kustomize-sops, pull requests merged in 2024-01, with the labels that each got.

#224 Fix typo in comment
  ksops.go
Labels: kind:documentation, size:XS, lgtm

#225 chore(deps): upgrade to kustomize v5.3.0
  go.mod
  go.sum
  scripts/install-kustomize.sh
Labels: kind:enhancement, size:XS, lgtm

#221 Using files together with secretFrom generates invalid yaml
  ksops.go
  test/legacy/multiple/generate-resources.yaml
  test/legacy/multiple/secret.enc.yaml
  test/legacy/multiple/want.yaml
Labels: kind:bug, size:M, lgtm
