Repository viaduct-ai/kustomize-sops, pull requests merged in 2024-05, with the labels that each got.

#241 update doc for argo-helm/argo-cd chart
  README.md
Labels: kind:documentation, size:XS, lgtm

#240 Allow passing a custom dir to install ksops to
  scripts/install-ksops-archive.sh
Labels: kind:enhancement, size:XS, lgtm

#233 chore(ci): Add DependaBot configuration for GitHub actions
  .github/dependabot.yml
Labels: kind:enhancement, size:S, lgtm

#232 chore(ci): Update GitHub action versions
  .github/workflows/codeql.yml
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: size:S, lgtm
